version: "3.8"

services:
  app:
    build: ./app
    container_name: crud_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=hoteles_db
      - DB_USER=postgres
      - DB_PASSWORD=PassDocker
    depends_on:
      - db
    networks:
      - slc-red

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=hoteles_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PassDocker
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - slc-red

networks:
  slc-red:

volumes:
  pgdata:
